alias ls='exa --icons --group-directories-first'
alias ll='exa --icons -l --git --group-directories-first'
alias la='exa --icons -a --group-directories-first'
alias update='sudo apt-get update && sudo apt-get upgrade'
alias clean='sudo apt-get autoremove'
alias c='clear'
alias df='df -h'
alias t='tmux attach'
alias tkill='tmux kill-server'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias nvc='cd && cd ~/.config/nvim/ && nvim'
alias sourceb='source ~/.bashrc'
alias install="dpkg -i"
